pytopo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('squidward/', include('squidward.urls')),
    path('', include('squidward.urls')),
]

squidward/forms.py
from django import forms


class SquidReportIndex(forms.Form):
    """

    """
    date_start = forms.DateField(label='Начало:',
                                 input_formats=['%m/%d/%Y'],
                                 )

    date_stop = forms.DateField(label='Конец:',
                                 input_formats=['%m/%d/%Y'])


class Login(forms.Form):
    """
    Simple login form
    """
    # login = forms.TextInput(label='Имя пользователя:')
    login = forms.CharField(label="Логин: ")
    # password = forms.PasswordInput(label='Пароль:', widget=forms.PasswordInput)
    password = forms.CharField(label="Пароль: ", widget=forms.PasswordInput())


class PPTP(forms.Form):
    """

    """

    ipaddress = forms.CharField(label='IP адрес', widget=forms.GenericIPAddressField())
    date_start = forms.DateField(label='Начало', input_formats=['%m/%d/%Y'])
    date_stop = forms.DateField(label='Конец', input_formats=['%m/%d/%Y'])

templates/base.html
<!DOCTYPE html>
<html>
<head>{% block head %}
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <script src="{% static 'js/jquery-1.12.4.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/fonts/fira_code.css' %}">



{% endblock %}</head>


<body>{% block body %}
{% block footer %}
    <img id="footer" src="{% static 'footer.jpg'%}">

{% endblock %}

    <nav class="nav nav-tabs">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <img width="55" src="{% static 'logo.png' %}">
      </a>
    </div>

    <ul class="nav navbar-nav">
      <li><a href="/">Главная</a></li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">PPTP
            <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="#">Проверить IP</a> </li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Настройки</a> </li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">Squidward
            <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'report_index' %}">Отчет за выбранный период</a> </li>
                <li><a href="{% url 'report_top_week' %}">Топ за прошлую неделю</a> </li>
                <li><a href="{% url 'report_top_month' %}">Топ за прошлый месяц</a> </li>
                <li role="separator" class="divider"></li>
                <li><a href="">Настройки</a> </li>
            </ul>
        </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      {% if current_user.is_authenticated %}
      <li><a href="">Сообщения: <span class="badge"></span>
          0
      </a></li>
      <li><a href="">Выйти <span class="glyphicon glyphicon-log-in"></span></a></li>

      {% else %}
      <li><a href="{% url 'login' %}">Вход <span class="glyphicon glyphicon-log-in"></span></a></li>
      {% endif %}
    </ul>
  </div>
</nav>


<div class="content">
{% block content %}

{% endblock %}
</div>


<div class="footer navbar-fixed-bottom row-fluid">
            &copy; 2018 wirr@wirr.pro
</div>


{% endblock %}</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Squidward is watching you{% endblock %}


{% block content %}

<div class="container" style="padding-top: 5%">

  <div class="col-sm-6">
      <img src="{% static 'squid.gif' %}" class="img-circle" alt="кальмар"/>
  </div>
  <div class="col-sm-6" align="right">
    <h1>Squidward - логи для УТОПО.</h1>
    <blockquote class="blockquote-reverse">
      <p>Установив систему защиты, не ждите благоприятных отзывов от сотрудников.</p>
      <p>Ни одно средство защиты, введенное в эксплуатацию, не прошло тестирования.</p>
      <p>Ни одно средство защиты, прошедшее тестирование, не готово к вводу в эксплуатацию (закон противоположности).</p>
      <p>Чем больше функций в системе защиты, тем больше вероятность, что одна из них не работает так как надо.</p>
        <footer><cite>Законы Мерфи (Наблюдения о средствах защиты).</cite></footer>
    </blockquote>
  </div>
</div>


{% endblock %}

templates/pptp_checkout_manual.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/pptp_checkout_manually.html
{% extends "base.html" %}
{% load static %}

{% block title %}Squidward is watching you!{% endblock %}

{% block head %}{{ block.super }}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <!--<link rel="stylesheet" href="/resources/demos/style.css">-->
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#datepicker-start" ).datepicker();
  } );
    $( function() {
    $( "#datepicker-end" ).datepicker();
  } );

  </script>
{% endblock %}
{% block content %}
    <div class="container">
    <div class="col-sm-12" align="center">
<form>
    <label>Начало:</label>
    <input type="text" id="datepicker-start">
    <label>Конец:</label>
    <input type="text"  id="datepicker-end">
  <button type="submit" class="btn btn-default">Сгенерировать</button>
</form>
     </div></div>







{% endblock %}



<div class="container">
	<div class="row">
 	    <div class="col-sm-12">
            <table class="table table-striped table-bordered">
                <thead class="thead-inverse">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">IP-адрес</th>
                        <th scope="col">Сайт</th>
                        <th scope="col">Мб</th>
                    </tr>
                </thead>
                <tbody>
                    {% for row in to_db %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            <td>1</td>
                            <td>2</td>
                            <td>3</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <ul class="pagination">
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
            </ul>
        </div>
    </div>
</div>

templates/pptp_checkout_report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/report_index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Squidward is watching you!{% endblock %}

{% block head %}{{ block.super }}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <!--<link rel="stylesheet" href="/resources/demos/style.css">-->
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  month_names = [
      "Январь", "Февраль", "Март", "Апрель",
      "Май", "Июнь", "Июль", "Август",
      "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"
  ]
  day_names = [
      "Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб",
  ]
  $( function() {
    $( "#id_date_start" ).datepicker({"monthNames": month_names,
        "dayNamesMin": day_names,
        "firstDay": 1});
  } );
    $( function() {
    $( "#id_date_stop" ).datepicker({"monthNames": month_names,
        "dayNamesMin": day_names,
        "firstDay": 1});

  } );

  </script>
{% endblock %}

{% block content %}

    <div class="index_report">
        <form id="choose_date" method="post">
            <caption><h5>База охватывает период {{ first_date }} - {{ last_date }}</h5></caption>


            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form.visible_fields %}
            <label>{{ field.label }}</label>{{ field }}
            {% endfor %}



        <button type="submit" class="btn btn-default" value="OK">Сгенерировать</button>
        </form>
    </div>
{% endblock %}





templates/report_manual.html
{% extends "base.html" %}
{% load static %}
{% block title %}Squidward is watching you{% endblock %}

{% block content %}
<div class="table_report">
            <table class="table table-striped table-bordered">
            <caption>Топ-50 пользователей с наибольшим трафиком {{ date_start }} - {{ date_stop }}</caption>
            <a class="backward" href="#" onclick="history.back();">Назад</a>
                <thead class="thead-inverse">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">IP-адрес</th>
                        <th scope="col">Мб</th>
                    </tr>
                </thead>
                <tbody class="tbody_report">
                    {% for row in pptp_sum %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="/reports/manual/{{ fromdate}}_{{ untildate }}/{{ row.pptpip }}">{{ row.pptpip }}</a></td>
                            <td>{{ row.sum }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
{#        </div>#}
{#    </div>#}
</div>
{% endblock %}

templates/report_manual_user.html
{% extends "base.html" %}
{% load static %}
{% block title %}Squidward is watching you{% endblock %}

{% block content %}

<div class="table_report">
            <table class="table table-striped table-bordered table-sm">
                <caption>Сайты, посещенные {{ user_ip }} в период {{ date_start }} - {{ date_stop }}</caption>
                            <a class="backward" href="#" onclick="history.back();">Назад</a>

                <thead class="thead-inverse">

                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Ресурс</th>
                        <th scope="col">Мб</th>
                    </tr>
                </thead>
                <tbody class="tbody_report">
                    {% for row in pptp_sum %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ row.resource }}</td>
                            <td>{{ row.sum }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}